# Generated by Django 4.0.2 on 2022-09-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_tipo_usr', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usr', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usr_nombre', models.CharField(max_length=40)),
                ('usr_apellido_pat', models.CharField(max_length=40)),
                ('usr_apellido_mat', models.CharField(max_length=40)),
                ('usr_pass', models.CharField(max_length=40)),
                ('usr_correo', models.CharField(max_length=100)),
                ('usr_activo', models.BooleanField(default=True)),
                ('usr_tipo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.tipo_usuario')),
            ],
        ),
    ]
