# Generated by Django 4.1.3 on 2022-11-26 23:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cupon',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_cupon', models.CharField(max_length=12)),
                ('cantidad', models.PositiveIntegerField()),
                ('Monto', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado_venta',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('Estado_venta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_venta',
            fields=[
                ('id_tipo_venta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('nro_orden', models.AutoField(primary_key=True, serialize=False)),
                ('bta_fecha', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 20, 5, 16, 439556), null=True)),
                ('cantidad_prod', models.PositiveIntegerField()),
                ('productos', models.CharField(max_length=50)),
                ('bta_Total', models.PositiveIntegerField()),
                ('id_Usuario_boleta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.usuario')),
                ('id_estado_boleta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrador.estado_venta')),
                ('id_tipo_boleta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrador.tipo_venta')),
            ],
        ),
    ]
