# Generated by Django 4.1.3 on 2022-11-26 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bta_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 20, 8, 3, 970408), null=True),
        ),
    ]
