# Generated by Django 4.1.2 on 2022-11-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cupon',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_cupon', models.CharField(max_length=12)),
                ('porcentaje', models.PositiveIntegerField()),
                ('Monto', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='rol_usuario',
            new_name='Rol',
        ),
    ]
