# Generated by Django 4.0.6 on 2022-11-27 03:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_venta',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('Estado_venta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_venta',
            fields=[
                ('id_tipo_venta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('nro_orden', models.AutoField(primary_key=True, serialize=False)),
                ('bta_fecha', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 0, 57, 23, 515270), null=True)),
                ('cantidad_prod', models.PositiveIntegerField()),
                ('productos', models.CharField(max_length=50)),
                ('bta_Total', models.PositiveIntegerField()),
                ('id_Usuario_boleta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_estado_boleta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrador.estado_venta')),
                ('id_tipo_boleta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrador.tipo_venta')),
            ],
        ),
    ]
