# Generated by Django 4.1.2 on 2022-11-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_cupon_rename_rol_usuario_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='porcentaje',
            new_name='cantidad',
        ),
    ]
