# Generated by Django 4.0.6 on 2022-11-27 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_estado_venta_tipo_venta_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bta_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 0, 57, 54, 808049), null=True),
        ),
    ]
