# Generated by Django 4.0.6 on 2022-11-27 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_alter_boleta_bta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bta_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 0, 59, 24, 651107), null=True),
        ),
    ]
