# Generated by Django 4.1.3 on 2022-11-27 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_alter_boleta_bta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='bta_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 2, 33, 48, 476014), null=True),
        ),
    ]
