# Generated by Django 4.1.3 on 2022-12-09 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0006_alter_reclamo_reclamo_fecha'),
        ('productos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_pedido',
            fields=[
                ('id_estado_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_venta',
            fields=[
                ('id_estado_venta', models.AutoField(primary_key=True, serialize=False)),
                ('estado_venta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_venta',
            fields=[
                ('id_tipo_venta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('vta_fecha', models.DateTimeField(auto_now=True)),
                ('vta_bruto', models.IntegerField(default=0)),
                ('vta_iva', models.IntegerField(default=0)),
                ('vta_propina', models.IntegerField(default=0)),
                ('vta_final', models.IntegerField(default=0)),
                ('vta_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.estado_venta')),
                ('vta_mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.mesa')),
                ('vta_tipo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipo_venta')),
            ],
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id_seleccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carrito')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_modif', models.CharField(max_length=200)),
                ('pedido_estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.estado_pedido')),
                ('pedido_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('pedido_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.venta')),
            ],
        ),
    ]
