# Generated by Django 4.1.4 on 2022-12-11 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '__first__'),
        ('productos', '0002_alter_categoria_prod_options_delete_pedido'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_pedido',
            fields=[
                ('id_estado_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='vta_mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.mesa'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vta_bruto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vta_fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vta_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vta_iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vta_propina',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_modif', models.CharField(max_length=200)),
                ('pedido_estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.estado_pedido')),
                ('pedido_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('pedido_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.venta')),
            ],
        ),
    ]
