# Generated by Django 4.1.2 on 2022-11-02 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('comuna_nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('dir_calle', models.CharField(max_length=50)),
                ('dir_nro', models.IntegerField()),
                ('dir_depto', models.BooleanField(default=False)),
                ('dir_depto_nro', models.IntegerField(null=True)),
                ('dir_comuna', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_reclamos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('apellido', models.CharField(max_length=40, null=True)),
                ('reclamo_fecha', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 2, 13, 24, 19, 45342), null=True)),
                ('reclamo_descrip', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('region_nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_tipo_usr', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usr', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usr_nombre', models.CharField(max_length=40)),
                ('usr_apellido_pat', models.CharField(max_length=40)),
                ('usr_apellido_mat', models.CharField(max_length=40)),
                ('usr_pass', models.CharField(max_length=40)),
                ('usr_correo', models.CharField(max_length=100)),
                ('usr_activo', models.BooleanField(default=True)),
                ('usr_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.direccion')),
                ('usr_tipo', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cliente.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('local_hora_aper', models.TimeField()),
                ('local_hora_cierr', models.TimeField()),
                ('local_fono', models.IntegerField()),
                ('local_activo', models.BooleanField(default=True)),
                ('locar_direccion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.direccion')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='comuna_region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.region'),
        ),
    ]
