<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-11-16 01:44
=======
# Generated by Django 4.0.6 on 2022-11-19 02:12
>>>>>>> 6889a0589f43f26f8b5b4ce9cf0ca55520b16982

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='reclamo_fecha',
<<<<<<< HEAD
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 15, 22, 44, 19, 962461), null=True),
=======
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 18, 23, 12, 18, 937059), null=True),
>>>>>>> 6889a0589f43f26f8b5b4ce9cf0ca55520b16982
        ),
    ]
