# Generated by Django 4.1.2 on 2022-10-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='comuna_region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.region'),
        ),
    ]
