# Generated by Django 4.0.6 on 2022-11-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_comuna_comuna_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMesa',
            fields=[
                ('id_estado_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('estado_mesa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('mesa_nro', models.IntegerField(max_length=2)),
                ('mesa_sillas', models.IntegerField(max_length=2)),
                ('mesa_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.estadomesa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField(max_length=40)),
                ('reserva_mesa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.mesa')),
                ('reserva_usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.usuario')),
            ],
        ),
    ]
