# Generated by Django 4.0.6 on 2022-11-19 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_reclamo_reclamo_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='reclamo_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 19, 6, 12, 35, 943221), null=True),
        ),
    ]
