# Generated by Django 4.0.6 on 2022-11-21 00:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_reclamo_reclamo_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='reserva_estado_mesa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.estadomesa'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='reclamo_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 21, 21, 52, 482307), null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(max_length=40),
        ),
    ]
