# Generated by Django 4.0.6 on 2022-11-21 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_reclamo_reclamo_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='reserva_estado_mesa',
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='reclamo_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 21, 41, 7, 171104), null=True),
        ),
    ]
