# Generated by Django 4.0.6 on 2022-11-21 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_rename_reserva_mesa_reserva_reserva_mesa_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='reserva_mesa_id',
            new_name='reserva_mesa',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='reserva_usuario_id',
            new_name='reserva_usuario',
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='reclamo_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 21, 46, 4, 1876), null=True),
        ),
    ]
