# Generated by Django 4.0.6 on 2022-11-21 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_rename_reserva_mesa_id_reserva_reserva_mesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_reserva',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='reclamo_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 22, 3, 31, 111448), null=True),
        ),
    ]
