# Generated by Django 4.0.6 on 2022-11-21 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_alter_reclamo_reclamo_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='reclamo_fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 23, 11, 44, 842653), null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_evento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.evento'),
        ),
    ]
