# Generated by Django 4.1.2 on 2022-11-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_prod',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_prod', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(max_length=100)),
                ('prod_descri', models.CharField(max_length=200)),
                ('prod_precio_ba', models.PositiveIntegerField()),
                ('prod_precio_of', models.PositiveIntegerField()),
                ('prod_imagen', models.FileField(default=None, upload_to='')),
                ('prod_disponible', models.BooleanField(default=True)),
                ('prod_recomendado', models.BooleanField(default=False)),
                ('prod_categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria_prod')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_modif', models.CharField(max_length=200)),
                ('pedido_listo', models.BooleanField(default=False)),
                ('pedido_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
