# Generated by Django 4.1.4 on 2022-12-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_prod',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
