# Generated by Django 4.1.1 on 2022-09-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(max_length=100)),
                ('prod_descri', models.CharField(max_length=200)),
                ('prod_precio_ba', models.IntegerField()),
                ('prod_precio_of', models.IntegerField()),
                ('prod_imagen', models.FileField(default=None, upload_to='media/%Y/%m/%d/')),
                ('prod_categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria_prod')),
            ],
        ),
    ]
