# Generated by Django 4.1.1 on 2022-10-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_prod_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prod_imagen',
            field=models.FileField(default=None, upload_to='productos/'),
        ),
    ]
